# 线上配置文件
spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://xxx.com:8081/usercenter?useSSL=false'
    username: codej
    password: rose!
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0